### ISSUE TITLE
Serverless Automatic needs --listen

### ISSUE THREAD

**Issue by fraankwang** [runpod/containers#11]
The workers won't actually be able to start up. I fixed this in my own build and it worked. https://github.com/runpod/containers/blob/main/serverless-automatic/start.sh#L7

**Comment by zhl146** [comment]
What kind of error are you getting that is preventing startup?

**Comment by justinmerrell** [comment]
--listen has been added, the worker has also been refactored and relocated here: https://github.com/runpod-workers/worker-a1111
