### ISSUE TITLE
Adding --api support to oobabooga/text-generation-web-ui

### ISSUE THREAD

**Issue by acidbubbles** [runpod/containers#13]
It would be very nice to have an environment variable to launch oobabooga (https://github.com/runpod/containers/blob/main/oobabooga/start.sh) with the API. See https://github.com/oobabooga/text-generation-webui#api for more information on this.

Otherwise, the only way to launch text-generation-web-ui with the API is to build my own docker image from scratch.

An alternative would be an ARGS environment variable to let us pass whatever we need to the python app.

Thank you for your consideration :)

**Comment by justinmerrell** [comment]
Added support for arguments to be passed with the even var `ADDITIONAL_FLAGS`, available in the image `runpod/oobabooga:1.2.1`
