### ISSUE TITLE
Tensorflow container has been deleted?

### ISSUE THREAD

**Issue by Inquisitive-ME** [runpod/containers#17]
I am trying to understand where this container comes from https://hub.docker.com/r/runpod/tensorflow
It links to this git repo but the folder has been deleted.

I would like to run a newer version of tensorflow but don't understand how I could update the container that currently exists in runpod for tensorflow

**Comment by justinmerrell** [comment]
Added back in, the latest one is `runpod/tensorflow:1.0.0`
