### ISSUE TITLE
TGI Docker file not able to access GPU?

### ISSUE THREAD

**Issue by solarslurpi** [runpod/containers#27]
I am creating a pod that uses HF's text-generation-interface (TGI) Docker container (see image_name below).  I can create a pod successfully as long as I do not pass in the --quantize parameter within the docker_args.  For example, if I pass in `docker_args="--model-id "tiiuae/falcon-7b-instruct" --num-shard 1 --quantize bitsandbytes" ` The error in the container log has...```2023-08-10T11:30:29.101220272-06:00 /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.``` and ends with the message: ```2023-08-10T11:30:29.101315592-06:00 ValueError: quantization is not available on CPU```  

HF support's comment when I asked on GitHub: **`it seems more to me that the GPU is not detected in the docker image, and that error message is bogus stemming from that. (I can run fine with 1.0.0 with bnb on a simple docker + gpu environement).` Another comment just made by HF GitHub: `Something about shm not being properly set or something.`..**.  If I try with the other quantization option `gptq`, the container throws a `signal 4`.  Is the container seeing the GPU?  What is going on with bitsandbytes?  Why signal 4.  I am hoping to minimize the amount of memory and inference time.  Help very much appreciated.

Here is my call to create_pod: ```pod = runpod.create_pod(
    name=model_id,
    image_name="ghcr.io/huggingface/text-generation-inference:1.0.0",
    gpu_type_id=gpu_type,
    cloud_type=cloud_type,
    docker_args=f"--model-id {model_id} --num-shard {num_shard} -quantize {quantize}",
    gpu_count=gpu_count,
    volume_in_gb=volume_in_gb,
    container_disk_in_gb=5,
    ports="80/http",
    volume_mount_path="/data",
    # min_vcpu_count=2,
    # min_memory_in_gb=15,
)``` The specs on my community pod is 1 x RTX 3090 9 vCPU 37 GB RAM.

Thank you.

**Comment by justinmerrell** [comment]
This sounds like a general question that should be submitted to our Discord or support chat. Unless I am missing something, there are no changes related to this repo. Closing. 

TGI has also released a new version https://github.com/huggingface/text-generation-inference/releases/tag/v1.0.3
