### ISSUE TITLE
Add Torch Vision to Comfy UI

### ISSUE THREAD

**Issue by jmrunpod** [runpod/containers#30]
Hello,

Template: https://github.com/runpod/containers/tree/main/official-templates/stable-diffusion-comfyui

User comment: 
> I'm trying to install ComfyUI Manager the standard way with git clone into the custom_nodes folder and it doesn't appear in the UI. I don't know of any other way. Am I missing something? 
> 
> OK nevermind. I figured it out. I had to install torch vision. The extension is 1.5MB and it's the basic one that let's you download other extensions, so it would be convenient to include it.

Thanks!
JM

**Comment by justinmerrell** [comment]
I think I noticed this as well and had a note that torch vision was causing issues. Made some changes and building a new version now.

**Comment by justinmerrell** [comment]
Done, correctly installed for `runpod/stable-diffusion:comfy-ui-3.0.1`
