### ISSUE TITLE
tensorflow template is always stuck on exporting environment variables

### ISSUE THREAD

**Issue by therealadityashankar** [runpod/containers#35]
![image](https://github.com/runpod/containers/assets/21975892/2845fc3e-ba3c-4349-9972-359222617009)

I tested this out with the tensorflow template on a 4090, it seems to never go ahead of "Exporting Environment variables"

**Comment by justinmerrell** [comment]
I believe the pod becomes ready but never prints anything else; I added another echo statement for `runpod/tensorflow:1.0.1`

![image](https://github.com/runpod/containers/assets/14996837/5e8b9daa-cf75-40b6-93ae-253db4625deb)

**Comment by therealadityashankar** [comment]
@justinmerrell the problem seems to be with jupyter as I notice it
![image](https://github.com/runpod/containers/assets/21975892/b3903525-7fb7-4ba1-bfa1-0756d39db087)

it never really starts up or connects, even though it says the pod is ready to use
![image](https://github.com/runpod/containers/assets/21975892/e30fec1d-e25b-4d65-8e22-7c075577c1ab)
