### ISSUE TITLE
Pytorch cuda image nvidia driver not installed?

### ISSUE THREAD

**Issue by crapthings** [runpod/containers#56]
<img width="1297" alt="image" src="https://github.com/runpod/containers/assets/1147704/0d8c6816-b77f-421a-b714-afadec7a3b7b">
<img width="1231" alt="image" src="https://github.com/runpod/containers/assets/1147704/ddcfb577-6b07-424c-9910-f5e3744760f3">

<img width="861" alt="image" src="https://github.com/runpod/containers/assets/1147704/48edcc59-46c3-489a-93f6-622437b41e30">

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by kodxana** [comment]
That is not RunPod issue as you run it on your own hardware. Drivers are handled on host level so it's saying that your PC do not have NVIDIA CUDA drivers installed.
