### ISSUE TITLE
Automatic WEBUI - Image to Image?

### ISSUE THREAD

**Issue by alelordelo** [runpod/containers#6]
The Automatic WEBUI is currently just hitting the text to Image endpoint:
check_api_availability("http://127.0.0.1:3000/sdapi/v1/txt2img")

How can we also hit the the Image to Image endpoint?

thanks

**Comment by kodxana** [comment]
Have you tried using http://127.0.0.1:3000/sdapi/v1/img2img ?

**Comment by alelordelo** [comment]
Nope...

How ca I call http://127.0.0.1:3000/sdapi/v1/img2img from runpod?

**Comment by zhl146** [comment]
there's a hardcoded txt2img endpoint in the start script, just change it to whatever you want
