### ISSUE TITLE
Automatic WEBUI - custom .ckpt or safe tensor not loaded

### ISSUE THREAD

**Issue by alelordelo** [runpod/containers#7]
I just followed the tutorial on RunPod Automatic WEBUI. and the custom safe tensor specified is not loaded when running inference. Instead, what is loaded is the default SD "model".

the the modded to load probably, we need to specify on this endpoint sdapi/v1/options:

"sd_model_checkpoint": "Anything-V3.0-pruned.ckpt [2700c435]",

response = requests.post(url=f'{url}/sdapi/v1/options', json=option_payload)

**Comment by kodxana** [comment]
Have you checked if your model is not corrupted?

**Comment by zhl146** [comment]
I think in my example, it renames it to a generic name. If you want to use a different name, then you would need to change the settings accordinly.
